### ISSUE TITLE
Current API returns semicolon-separated synonyms

### ISSUE THREAD

**Issue by rinunu** [MyAnimeList/mal-api-docs#1]
> Use actual arrays for multi-value fields.

**Comment by rinunu** [comment]
Since the internal format of Anime#synonyms is so jumbled, until we reformat the data we can not return that field as structured format.

**Comment by erengy** [comment]
Possible solutions to avoid introducing a backwards-incompatible change:

1. Return `synonyms` as an array by splitting the string with "; " (this is currently what all clients do). Once you reformat the internal data, it'll be a seamless change for the clients.

2. Rename `synonyms` to something else, such as `synonyms_all`. Once you reformat the internal data, introduce `synonyms` as an array and deprecate `synonyms_all`.

3. Document that `synonyms` can be either a string or an array, and that clients should check the value type before parsing it.

**Comment by rinunu** [comment]
@erengy 
I want to return synonyms as an array, but occasionally it contains data with different format.
For example:
https://myanimelist.net/anime/34134/One_Punch_Man_2

I think that we can fix the data and fix JSON format by α or 1.0 if the amount of incorrect data is small.

Thank you for the comment.

**Comment by erengy** [comment]
You mean synonyms being separated by a comma rather than a semicolon, right? I found ~50 anime with this issue in my local (incomplete and outdated) database. They can be fixed by anime DB moderators, but some measures should be taken to avoid future problems.

Note that when you return synonyms as a string, clients expect them to be semicolon-separated. We cannot programmatically split those comma-separated erroneous synonyms either. So I think splitting the synonyms on the server and returning an array is still a better idea.

**Comment by rinunu** [comment]
> right?
Yes.

I agree.
I will consult with kineta.

**Comment by rinunu** [comment]
I made synonyms an array.
https://myanimelist.github.io/mal-api-docs/#operation/anime_get

Mods will fix the internal data format.
